Repository JNU-econovation/Whoz-in-BE, pull requests merged in 2025-03, with the labels that each got.

#234 [FIX] active device 판별 로직 수정
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceEntity.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/InActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/ActiveTimeUpdateDeterminer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/DeviceTimeComparators.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/DeviceUtils.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/InActiveMemberConnectionManager.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/exception/NotFoundConnectionInfoException.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberDetailInfoGet.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberDetailInfoHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoom.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/response/MemberInRoomResponse.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/response/MembersInRoomResponse.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberAuthInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberConnectionInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberDetailInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/MemberQueryController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/ActiveDeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/DeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/DeviceStatusManager.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java
Labels: bug

#237 [FEAT] Active Device 삭제 기능
  .github/workflows/main-api-deploy.yml
  .github/workflows/network-api-deploy.yml
  modules/domain/src/main/java/com/whoz_in/domain/device/event/DeviceDeleted.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/device/application/DeviceRemoveHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/event/DeviceDeletedEvent.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/event/DeviceDeletedEventHandler.java
Labels: feat

#238 [REFACTOR] 기기 삭제 시, 기기가 가지고 있던 연속 접속 시간 정보 누적 로직 추가
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
Labels: feat

#241 [REFACTOR] 동방 현황 조회 로직 수정
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/DeviceJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/view/ActiveDeviceViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/device/view/DeviceViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/response/MemberInRoomResponse.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberInfo.java
Labels: Refactor

#240 [FEAT] Event Retry
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/event/fail/FailedEventRetryer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/event/fail/FailedEventStore.java
Labels: feat

#248 [REFACTOR] 이벤트 재시도 로직 제거
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/event/fail/FailedEventRetryer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/event/fail/FailedEventStore.java
Labels: Refactor

#244 [REFACTOR] device register event
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDayEndEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/InActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/ActiveTimeUpdateDeterminer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/ActiveTimeUpdateWriter.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/DeviceTimeComparators.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/DeviceUtils.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/util/InActiveMemberConnectionManager.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/ActiveDeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/event/DeviceCreatedEventHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/member/event/DayEndEvent.java
Labels: Refactor

#251 [REFACTOR] 동아리 방 현황 조회 로직 수정
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/main-api-deploy.yml
  .github/workflows/main-api.yml
  .github/workflows/network-api.yml
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberConnectionInfoRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceService.java
  modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityFilterChainConfig.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/view/ActiveDeviceViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberCountInRoom.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberCountInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoom.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/response/MemberCountInRoomResponse.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/MemberQueryController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/docs/MemberQueryApi.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/member/event/DayEndEvent.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/utils/Sorter.java
  modules/main-api/src/test/java/com/whoz_in/main_api/shared/utils/SorterTest.java
Labels: Refactor

#252 [REFACTOR] GitHub Action workflow를 수정합니다.
  .github/workflows/deploy.yml
  .github/workflows/network-api.yml
Labels: Refactor

#253 [REFACTOR] GitHub workflow 수정
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/main-api.yml
  .github/workflows/network-api.yml
Labels: Refactor

#256 [REFACTOR] ci 트리거 이벤트 수정
  .github/workflows/ci.yml
Labels: Refactor

#257 [REFACTOR] 동방 현확 파악 로직을 수정합니다.
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/monitor/MonitorLogEntityRepository.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/ActiveDeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/DeviceFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java
  modules/main-api/src/test/java/com/whoz_in/main_api/shared/domain/device/DeviceFixture.java
  modules/main-api/src/test/java/com/whoz_in/main_api/shared/domain/device/DeviceInfoFixture.java
  modules/main-api/src/test/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilterTest.java
  modules/main-api/src/test/java/com/whoz_in/main_api/shared/domain/member/MemberFixture.java
Labels: Refactor

#255 [FEAT] voc 기능에 제목 추가
  modules/domain/src/main/java/com/whoz_in/domain/feedback/event/FeedbackCreated.java
  modules/domain/src/main/java/com/whoz_in/domain/feedback/model/Feedback.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackConverter.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackEntity.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/application/FeedbackSend.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/application/FeedbackSendHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/exception/ContentLengthExceedException.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/exception/TitleLengthExceededException.java
Labels: feat

#259 [FIX] active member query 수정
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberRepository.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
Labels: Refactor

#267 [REFACTOR] workflow 실행 조건부로 변경
  .github/workflows/deploy.yml
  .github/workflows/main-api.yml
  .github/workflows/network-api.yml
Labels: Refactor

#268 [REFACTOR] AccessToken 에 token ID 를 제거합니다.
  modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/command/LogOut.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/command/LogOutHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/member/presentation/MemberController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/config/security/AccessTokenFilter.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/jwt/tokens/AccessToken.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/jwt/tokens/AccessTokenSerializer.java
Labels: Refactor

#265 [FIX] 동아리 방 재실 시간 조회 오류 수정
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDayEndEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/InActiveDeviceEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberConnectionInfo.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/member/presentation/MemberController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberConnectionInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/member/event/DayEndEvent.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/jwt/tokens/AccessToken.java
  modules/main-api/src/main/java/com/whoz_in/main_api/shared/jwt/tokens/StubTokenStore.java
Labels: bug

#272 [FIX] UpdateDailyTime 메소드를 수정합니다.
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java
Labels: bug

#273 [FIX] Transactional Propagation 종류를 수정합니다.
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java
Labels: Refactor

#143 [FEAT] 뱃지 작업
  modules/domain/src/main/java/com/whoz_in/domain/badge/BadgeRepository.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/event/BadgeCreated.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/exception/AlreadyHasBadgeException.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/exception/InvalidBadgeRegisterException.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/exception/InvalidFormColorCodeException.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/exception/NoBadgeException.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/exception/SameBadgeExistException.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/model/Badge.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/model/BadgeId.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/model/BadgeInfo.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/model/BadgeType.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/service/BadgeFinderService.java
  modules/domain/src/main/java/com/whoz_in/domain/badge/service/BadgeOwnershipService.java
  modules/domain/src/main/java/com/whoz_in/domain/member/event/MemberBadgeChanged.java
  modules/domain/src/main/java/com/whoz_in/domain/member/model/Member.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/badge/Badge.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/badge/BadgeJpaViewer.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/badge/BadgeMember.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/badge/BadgeMemberRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/badge/BadgeRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeConverter.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeEntity.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeEntityRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeJpaRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeMemberEntity.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeMemberEntityRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/badge/BadgeMemberId.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/member/MemberConverter.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/member/MemberEntity.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/member/MemberJpaRepository.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeAttach.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeAttachHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeRegister.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeRegisterHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeSwitchVisibility.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/application/BadgeSwitchVisibilityHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/presentation/BadgeCommandController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/badge/presentation/docs/BadgeCommandApi.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/CreateBadgeOnMemberCreated.java
  modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityFilterChainConfig.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/BadgeViewer.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/handler/BadgeInfoViewHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/handler/BadgeOfMemberViewHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/handler/RegistrableBadgeViewHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/query/BadgeInfoGet.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/query/MemberBadgeQuery.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/query/RegistrableBadgeQuery.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/response/BadgeInfoResponse.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/view/BadgeInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/view/BadgesOfMember.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/application/view/RegistrableBadges.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/presentatiion/BadgeQueryController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/badge/presentatiion/docs/BadgeQueryApi.java
Labels: feat

#289 [FIX] 사용자 재실 시간 정밀도 상향
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java
Labels: bug

#294 [FIX] Device 삭제 로직 수정 및 삭제 메소드 추가
  modules/domain/src/main/java/com/whoz_in/domain/device/DeviceRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/device/DeviceEntityRepository.java
  modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/device/DeviceJpaRepository.java
  modules/main-api/src/main/java/com/whoz_in/main_api/command/device/application/DeviceRemoveHandler.java
Labels: bug

#299 [FAET] 회원 Profile 조회 API / 시간 초기화 로직 수정
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberRepository.java
  modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/event/MemberDayEndEventHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberProfile.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberProfileHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/response/MemberProfileInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/view/MemberConnectionInfo.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/MemberQueryController.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/docs/MemberQueryApi.java
Labels: bug, Refactor

#304 [REFACTOR] 다른 회원 프로필 조회 수정
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MemberProfileHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/query/MembersInRoomHandler.java
  modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/support/ConnectionTimeFormatter.java
Labels: Refactor
